import type { Metadata } from "next";
import { Geist, Geist_Mono, Monomaniac_One, Ubuntu } from "next/font/google";
import "./globals.css";

const geistSans = Ubuntu({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400","500", "700"],});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} $antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
